### PR TITLE
Remove Custom Overlay

### PR DESCRIPTION
**Pull request by LukePulverenti**
And use the one embedded in the Emby package. Among other things, this will allow the dotnet runtime to be used instead of the mono runtime.

### CODE REVIEW

**Comment by Baenwort** [comment]
This works to fix the problem I'm having with building a dev branch plug-in. With this change my https://github.com/Baenwort/iocage-plugin-index/blob/master/emby.json plug in works!

**Comment by LukePulverenti** [comment]
> This works to fix the problem I'm having with building a dev branch plug-in. With this change my https://github.com/Baenwort/iocage-plugin-index/blob/master/emby.json plug in works!

Yea if we can get this merged and then updated in TrueNAS this is going to help with a lot of the problems users are having.

**Comment by Baenwort** [comment]
It looks like this https://github.com/freenas/iocage-plugin-emby/issues/9#issuecomment-1215276624 is also trying to fix the same issue. It seems to be more active so perhaps one of the two will get merged and we can all be happy!

**Comment by jasker5183** [comment]
Closed my issue and PR as I inadvertently filed a duplicate. Is there any way we can expedite this or is it advantageous to roll broken plugins?

**Review by sonicaj — APPROVED** [review]

**Pull request merged**
